/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.client.api;

import com.camunda.consulting.client.model.SchemaLogEntryDto;
import com.camunda.consulting.client.model.SchemaLogQueryDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchemaLogApi
 */
@Ignore
public class SchemaLogApiTest {

    private final SchemaLogApi api = new SchemaLogApi();

    
    /**
     * 
     *
     * Queries for schema log entries that fulfill given parameters.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchemaLogTest() {
        String version = null;
        Integer firstResult = null;
        Integer maxResults = null;
        List<SchemaLogEntryDto> response = api.getSchemaLog(version, firstResult, maxResults);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Queries for schema log entries that fulfill given parameters.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void querySchemaLogTest() {
        Integer firstResult = null;
        Integer maxResults = null;
        SchemaLogQueryDto schemaLogQueryDto = null;
        List<SchemaLogEntryDto> response = api.querySchemaLog(firstResult, maxResults, schemaLogQueryDto);

        // TODO: test validations
    }
    
}
