/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.client.api;

import com.camunda.consulting.client.model.VersionDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersionApi
 */
@Ignore
public class VersionApiTest {

    private final VersionApi api = new VersionApi();

    
    /**
     * 
     *
     * Retrieves the version of the Rest API.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRestAPIVersionTest() {
        VersionDto response = api.getRestAPIVersion();

        // TODO: test validations
    }
    
}
