/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * MultiFormAttachmentDto
 */
@JsonPropertyOrder({
  MultiFormAttachmentDto.JSON_PROPERTY_ATTACHMENT_NAME,
  MultiFormAttachmentDto.JSON_PROPERTY_ATTACHMENT_DESCRIPTION,
  MultiFormAttachmentDto.JSON_PROPERTY_ATTACHMENT_TYPE,
  MultiFormAttachmentDto.JSON_PROPERTY_URL,
  MultiFormAttachmentDto.JSON_PROPERTY_CONTENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-20T14:06:02.786934+02:00[Europe/Berlin]")
public class MultiFormAttachmentDto {
  public static final String JSON_PROPERTY_ATTACHMENT_NAME = "attachment-name";
  private String attachmentName;

  public static final String JSON_PROPERTY_ATTACHMENT_DESCRIPTION = "attachment-description";
  private String attachmentDescription;

  public static final String JSON_PROPERTY_ATTACHMENT_TYPE = "attachment-type";
  private String attachmentType;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private JsonNullable<File> content = JsonNullable.<File>undefined();


  public MultiFormAttachmentDto attachmentName(String attachmentName) {
    
    this.attachmentName = attachmentName;
    return this;
  }

   /**
   * The name of the attachment.
   * @return attachmentName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the attachment.")
  @JsonProperty(JSON_PROPERTY_ATTACHMENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAttachmentName() {
    return attachmentName;
  }


  public void setAttachmentName(String attachmentName) {
    this.attachmentName = attachmentName;
  }


  public MultiFormAttachmentDto attachmentDescription(String attachmentDescription) {
    
    this.attachmentDescription = attachmentDescription;
    return this;
  }

   /**
   * The description of the attachment.
   * @return attachmentDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The description of the attachment.")
  @JsonProperty(JSON_PROPERTY_ATTACHMENT_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAttachmentDescription() {
    return attachmentDescription;
  }


  public void setAttachmentDescription(String attachmentDescription) {
    this.attachmentDescription = attachmentDescription;
  }


  public MultiFormAttachmentDto attachmentType(String attachmentType) {
    
    this.attachmentType = attachmentType;
    return this;
  }

   /**
   * The type of the attachment.
   * @return attachmentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of the attachment.")
  @JsonProperty(JSON_PROPERTY_ATTACHMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAttachmentType() {
    return attachmentType;
  }


  public void setAttachmentType(String attachmentType) {
    this.attachmentType = attachmentType;
  }


  public MultiFormAttachmentDto url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The url to the remote content of the attachment.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The url to the remote content of the attachment.")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public MultiFormAttachmentDto content(File content) {
    this.content = JsonNullable.<File>of(content);
    
    return this;
  }

   /**
   * The content of the attachment.
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The content of the attachment.")
  @JsonIgnore

  public File getContent() {
        return content.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<File> getContent_JsonNullable() {
    return content;
  }
  
  @JsonProperty(JSON_PROPERTY_CONTENT)
  public void setContent_JsonNullable(JsonNullable<File> content) {
    this.content = content;
  }

  public void setContent(File content) {
    this.content = JsonNullable.<File>of(content);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiFormAttachmentDto multiFormAttachmentDto = (MultiFormAttachmentDto) o;
    return Objects.equals(this.attachmentName, multiFormAttachmentDto.attachmentName) &&
        Objects.equals(this.attachmentDescription, multiFormAttachmentDto.attachmentDescription) &&
        Objects.equals(this.attachmentType, multiFormAttachmentDto.attachmentType) &&
        Objects.equals(this.url, multiFormAttachmentDto.url) &&
        Objects.equals(this.content, multiFormAttachmentDto.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachmentName, attachmentDescription, attachmentType, url, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiFormAttachmentDto {\n");
    sb.append("    attachmentName: ").append(toIndentedString(attachmentName)).append("\n");
    sb.append("    attachmentDescription: ").append(toIndentedString(attachmentDescription)).append("\n");
    sb.append("    attachmentType: ").append(toIndentedString(attachmentType)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

