/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * MultiFormDeploymentDto
 */
@JsonPropertyOrder({
  MultiFormDeploymentDto.JSON_PROPERTY_TENANT_ID,
  MultiFormDeploymentDto.JSON_PROPERTY_DEPLOYMENT_SOURCE,
  MultiFormDeploymentDto.JSON_PROPERTY_DEPLOY_CHANGED_ONLY,
  MultiFormDeploymentDto.JSON_PROPERTY_ENABLE_DUPLICATE_FILTERING,
  MultiFormDeploymentDto.JSON_PROPERTY_DEPLOYMENT_NAME,
  MultiFormDeploymentDto.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-20T14:06:02.786934+02:00[Europe/Berlin]")
public class MultiFormDeploymentDto {
  public static final String JSON_PROPERTY_TENANT_ID = "tenant-id";
  private String tenantId;

  public static final String JSON_PROPERTY_DEPLOYMENT_SOURCE = "deployment-source";
  private String deploymentSource;

  public static final String JSON_PROPERTY_DEPLOY_CHANGED_ONLY = "deploy-changed-only";
  private JsonNullable<Boolean> deployChangedOnly = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_ENABLE_DUPLICATE_FILTERING = "enable-duplicate-filtering";
  private JsonNullable<Boolean> enableDuplicateFiltering = JsonNullable.<Boolean>of(false);

  public static final String JSON_PROPERTY_DEPLOYMENT_NAME = "deployment-name";
  private String deploymentName;

  public static final String JSON_PROPERTY_DATA = "data";
  private JsonNullable<File> data = JsonNullable.<File>undefined();


  public MultiFormDeploymentDto tenantId(String tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

   /**
   * The tenant id for the deployment to be created.
   * @return tenantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tenant id for the deployment to be created.")
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantId() {
    return tenantId;
  }


  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public MultiFormDeploymentDto deploymentSource(String deploymentSource) {
    
    this.deploymentSource = deploymentSource;
    return this;
  }

   /**
   * The source for the deployment to be created.
   * @return deploymentSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The source for the deployment to be created.")
  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeploymentSource() {
    return deploymentSource;
  }


  public void setDeploymentSource(String deploymentSource) {
    this.deploymentSource = deploymentSource;
  }


  public MultiFormDeploymentDto deployChangedOnly(Boolean deployChangedOnly) {
    this.deployChangedOnly = JsonNullable.<Boolean>of(deployChangedOnly);
    
    return this;
  }

   /**
   * A flag indicating whether the process engine should perform duplicate checking on a per-resource basis. If set to true, only those resources that have actually changed are deployed. Checks are made against resources included previous deployments of the same name and only against the latest versions of those resources. If set to true, the option enable-duplicate-filtering is overridden and set to true.
   * @return deployChangedOnly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A flag indicating whether the process engine should perform duplicate checking on a per-resource basis. If set to true, only those resources that have actually changed are deployed. Checks are made against resources included previous deployments of the same name and only against the latest versions of those resources. If set to true, the option enable-duplicate-filtering is overridden and set to true.")
  @JsonIgnore

  public Boolean getDeployChangedOnly() {
        return deployChangedOnly.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DEPLOY_CHANGED_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getDeployChangedOnly_JsonNullable() {
    return deployChangedOnly;
  }
  
  @JsonProperty(JSON_PROPERTY_DEPLOY_CHANGED_ONLY)
  public void setDeployChangedOnly_JsonNullable(JsonNullable<Boolean> deployChangedOnly) {
    this.deployChangedOnly = deployChangedOnly;
  }

  public void setDeployChangedOnly(Boolean deployChangedOnly) {
    this.deployChangedOnly = JsonNullable.<Boolean>of(deployChangedOnly);
  }


  public MultiFormDeploymentDto enableDuplicateFiltering(Boolean enableDuplicateFiltering) {
    this.enableDuplicateFiltering = JsonNullable.<Boolean>of(enableDuplicateFiltering);
    
    return this;
  }

   /**
   * A flag indicating whether the process engine should perform duplicate checking for the deployment or not. This allows you to check if a deployment with the same name and the same resouces already exists and if true, not create a new deployment but instead return the existing deployment. The default value is false.
   * @return enableDuplicateFiltering
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A flag indicating whether the process engine should perform duplicate checking for the deployment or not. This allows you to check if a deployment with the same name and the same resouces already exists and if true, not create a new deployment but instead return the existing deployment. The default value is false.")
  @JsonIgnore

  public Boolean getEnableDuplicateFiltering() {
        return enableDuplicateFiltering.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ENABLE_DUPLICATE_FILTERING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getEnableDuplicateFiltering_JsonNullable() {
    return enableDuplicateFiltering;
  }
  
  @JsonProperty(JSON_PROPERTY_ENABLE_DUPLICATE_FILTERING)
  public void setEnableDuplicateFiltering_JsonNullable(JsonNullable<Boolean> enableDuplicateFiltering) {
    this.enableDuplicateFiltering = enableDuplicateFiltering;
  }

  public void setEnableDuplicateFiltering(Boolean enableDuplicateFiltering) {
    this.enableDuplicateFiltering = JsonNullable.<Boolean>of(enableDuplicateFiltering);
  }


  public MultiFormDeploymentDto deploymentName(String deploymentName) {
    
    this.deploymentName = deploymentName;
    return this;
  }

   /**
   * The name for the deployment to be created.
   * @return deploymentName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name for the deployment to be created.")
  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeploymentName() {
    return deploymentName;
  }


  public void setDeploymentName(String deploymentName) {
    this.deploymentName = deploymentName;
  }


  public MultiFormDeploymentDto data(File data) {
    this.data = JsonNullable.<File>of(data);
    
    return this;
  }

   /**
   * The binary data to create the deployment resource. It is possible to have more than one form part with different form part names for the binary data to create a deployment.
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The binary data to create the deployment resource. It is possible to have more than one form part with different form part names for the binary data to create a deployment.")
  @JsonIgnore

  public File getData() {
        return data.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<File> getData_JsonNullable() {
    return data;
  }
  
  @JsonProperty(JSON_PROPERTY_DATA)
  public void setData_JsonNullable(JsonNullable<File> data) {
    this.data = data;
  }

  public void setData(File data) {
    this.data = JsonNullable.<File>of(data);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiFormDeploymentDto multiFormDeploymentDto = (MultiFormDeploymentDto) o;
    return Objects.equals(this.tenantId, multiFormDeploymentDto.tenantId) &&
        Objects.equals(this.deploymentSource, multiFormDeploymentDto.deploymentSource) &&
        Objects.equals(this.deployChangedOnly, multiFormDeploymentDto.deployChangedOnly) &&
        Objects.equals(this.enableDuplicateFiltering, multiFormDeploymentDto.enableDuplicateFiltering) &&
        Objects.equals(this.deploymentName, multiFormDeploymentDto.deploymentName) &&
        Objects.equals(this.data, multiFormDeploymentDto.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, deploymentSource, deployChangedOnly, enableDuplicateFiltering, deploymentName, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiFormDeploymentDto {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    deploymentSource: ").append(toIndentedString(deploymentSource)).append("\n");
    sb.append("    deployChangedOnly: ").append(toIndentedString(deployChangedOnly)).append("\n");
    sb.append("    enableDuplicateFiltering: ").append(toIndentedString(enableDuplicateFiltering)).append("\n");
    sb.append("    deploymentName: ").append(toIndentedString(deploymentName)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

