/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MultiFormAttachmentDto
 */
public class MultiFormAttachmentDtoTest {
    private final MultiFormAttachmentDto model = new MultiFormAttachmentDto();

    /**
     * Model tests for MultiFormAttachmentDto
     */
    @Test
    public void testMultiFormAttachmentDto() {
        // TODO: test MultiFormAttachmentDto
    }

    /**
     * Test the property 'attachmentName'
     */
    @Test
    public void attachmentNameTest() {
        // TODO: test attachmentName
    }

    /**
     * Test the property 'attachmentDescription'
     */
    @Test
    public void attachmentDescriptionTest() {
        // TODO: test attachmentDescription
    }

    /**
     * Test the property 'attachmentType'
     */
    @Test
    public void attachmentTypeTest() {
        // TODO: test attachmentType
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

}
