/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MultiFormDeploymentDto
 */
public class MultiFormDeploymentDtoTest {
    private final MultiFormDeploymentDto model = new MultiFormDeploymentDto();

    /**
     * Model tests for MultiFormDeploymentDto
     */
    @Test
    public void testMultiFormDeploymentDto() {
        // TODO: test MultiFormDeploymentDto
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'deploymentSource'
     */
    @Test
    public void deploymentSourceTest() {
        // TODO: test deploymentSource
    }

    /**
     * Test the property 'deployChangedOnly'
     */
    @Test
    public void deployChangedOnlyTest() {
        // TODO: test deployChangedOnly
    }

    /**
     * Test the property 'enableDuplicateFiltering'
     */
    @Test
    public void enableDuplicateFilteringTest() {
        // TODO: test enableDuplicateFiltering
    }

    /**
     * Test the property 'deploymentName'
     */
    @Test
    public void deploymentNameTest() {
        // TODO: test deploymentName
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
