/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.camunda.consulting.client.model;

import com.camunda.consulting.client.model.SortTaskQueryParametersDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaskQueryDtoSorting
 */
public class TaskQueryDtoSortingTest {
    private final TaskQueryDtoSorting model = new TaskQueryDtoSorting();

    /**
     * Model tests for TaskQueryDtoSorting
     */
    @Test
    public void testTaskQueryDtoSorting() {
        // TODO: test TaskQueryDtoSorting
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    public void sortByTest() {
        // TODO: test sortBy
    }

    /**
     * Test the property 'sortOrder'
     */
    @Test
    public void sortOrderTest() {
        // TODO: test sortOrder
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

}
